[package]
name = "sc-allocator"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Collection of allocator implementations."
documentation = "https://docs.rs/sc-allocator"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-std = { version = "4.0.0-dev", path = "../../primitives/std", default-features = false }
sp-core = { version = "4.0.0-dev", path = "../../primitives/core", default-features = false }
sp-wasm-interface = { version = "4.0.0-dev", path = "../../primitives/wasm-interface", default-features = false }
log = { version = "0.4.11", optional = true }
thiserror = { version = "1.0.21" }

[features]
default = [ "std" ]
std = [
	"sp-std/std",
	"sp-core/std",
	"sp-wasm-interface/std",
	"log",
]
